### ISSUE TITLE
Support pg_embedding for storing embedding 

### ISSUE THREAD

**Issue by diptanu** [diptanu/indexify#110]
Support pg_embedding to store embedding vectors.

Sub Tasks 
* Add a server configuration block to support postgres as the vector store. For example - 
   ```
     index_config:
        index_store: postgres
     postgres_config:
        addr: postgres://postgres:postgres@postgres/indexify_embeddings
   ```
* Add a Postgres implementation for the vectordb Rust interface - https://github.com/diptanu/indexify/blob/main/src/vectordbs/mod.rs#L85
* Add tests similar to what we have for qdrant
